import { describe, expect, it } from "vitest";
// Cross-project import (operator decision for issue #9): single source of
// truth is the snapshot at tests/snapshots/pairing_payload.schema.json,
// generated by `uv run python scripts/dump_schemas.py`. Pulling it directly
// avoids a parallel copy in web/.
import schema from "../../../tests/snapshots/pairing_payload.schema.json";

/**
 * Drift guard. When the Python `PairingPayload.model_json_schema()` snapshot
 * changes, this test fails. To fix, either:
 *   1. Refresh the snapshot:
 *        uv run python scripts/dump_schemas.py > tests/snapshots/pairing_payload.schema.json
 *   2. Update EXPECTED_KEYS below and the `PairingState` interface
 *      in `web/src/types/pairing.ts` to match.
 */
const EXPECTED_KEYS = [
  "connected",
  "detail",
  "event",
  "expires_at",
  "logged_in",
  "qr_available",
  "reachable",
  "supported",
  "updated_at",
].sort();

describe("PairingState matches the Python PairingPayload schema", () => {
  it("has the expected property keys", () => {
    const properties = (schema as { properties: Record<string, unknown> })
      .properties;
    expect(Object.keys(properties).sort()).toEqual(EXPECTED_KEYS);
  });
});
